from .model_tab import run_tab_model
from .select_data_tab import run_tab_select_data
from .configure_tab import run_tab_configure
from .view_tab import run_tab_view
from .metrics_tab import run_tab_metrics
from .predict_tab import run_tab_predict
from .visualize_tab import run_tab_visualize
from .feature_comparison_tab import run_tab_feature_comparison
from .export_tab import run_tab_export
from .ai_summary_tab import run_tab_ai_summary
